version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hmis
      POSTGRES_DB: sac_hmis_db
  app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    environment:
      DATABASE_URL: postgresql://root:hmis@db:5432/sac_hmis_db
    depends_on:
      - db
